application: amazonpredictor
version: 1

runtime: python27
api_version: 1
threadsafe: false

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$

handlers:
- url: /(.*\.(gif|png|jpg|ico|css|js))
  static_files: \1
  upload: .*\.(gif|png|jpg|ico|css|js)
- url: /(post|get)?
  script: index.app
  secure: always
